# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: BuildAndDeploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: mkdir ./src/config/env
    - run: touch ./src/config/env/.prod.env
    - run: echo '${{ secrets.PROD_ENV }}' > ./src/config/env/.prod.env
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/everyslang-api-server:latest
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker image pull ${{ secrets.DOCKER_HUB_USERNAME }}/everyslang-api-server:latest
          sudo docker container run -d -p 80:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/everyslang-api-server:latest
